# Generated by Django 4.0.1 on 2022-01-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalcomputer',
            options={'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
    ]
