# Generated by Django 4.0.1 on 2022-01-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_personalcomputer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcomputer',
            name='mac_address',
            field=models.CharField(max_length=17, verbose_name='Мак адрес'),
        ),
    ]
